name: one_request
description: A Flutter package for making HTTP requests with advanced error handling, logging, retry logic, caching, and batch requests using Dio.
version: 3.0.0
homepage: https://github.com/snigdho48/one_request
repository: https://github.com/snigdho48/one_request/
issue_tracker: https://github.com/snigdho48/one_request/issues/
environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.11.0
  dart_either: ^2.3.0
  flutter_easyloading: ^4.0.2
  logging: ^1.3.0
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.6.0
