name: one_request
description: A Flutter package to make HTTP requests with advanced error handling, including Dio and EasyLoading.
version: 2.0.6
homepage: https://github.com/snigdho48/one_request
repository: https://github.com/snigdho48/one_request/
issue_tracker: https://github.com/snigdho48/one_request/issues/
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
